### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by mikaelcom** [Orange-OpenSource/Orange-Confort-plus#11]
Hi,

After having cliked on the + icon once in order to show the Comfort toolbar, when I click a second time (in order to hide the comfort toolbar as I would expect it to work), I get this error:
- Uncaught TypeError: Cannot read property 'style' of null
- Trace:

```
UciIhm.close_menu   @   toolbar-min.js:11
accessibilitytoolbar.hide   @   toolbar-min.js:13
accessibilitytoolbar.toggle @   toolbar-min.js:13
```

**Comment by Lausselloic** [comment]
Hello,

Sorry for the late reply I just see it.

I can't reproduce it. Your trace indicate that the style property onto document.getElementById('uci_cdu_menu') doesn't exist but this element is created by the toolbar, and is present.

Can you tell me more about this case? Which browser and version? Which url? So I can make more investigation and add a test case, but I want to understand how those error can be throw.

**Comment by mikaelcom** [comment]
The issue is present using Google Chrome that does not allow cross domain cookies
