### ISSUE TITLE
Does not init on XHTML page

### ISSUE THREAD

**Issue by smonsarr** [Orange-OpenSource/Orange-Confort-plus#12]
It seems that Orange + extention for Firefox does not init on XHTML pages.
Console output : 
not well-formed(unknown)
mismatched tag. Expected: </input>.

**Comment by Lausselloic** [comment]
Hello,

Can you provide more information to reproduce the bug? Can you give a URL? Onto wich browser and version does it appear?

I've tried onto Chrome, FF, and IE11 with an empty page like that : 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtmlxml:lang="fr" lang="fr">
  <head>
    <title>
    </title>
  </head>
  <body>
  </body>
</html>

And doesn't reproduce the error.

**Comment by smonsarr** [comment]
Example : 
https://christophe-rhein.canoprof.fr/eleve/Mes%20formations/Formation%20%C3%A0%20quelques%20outils%20Google/index.xhtml

**Comment by smonsarr** [comment]
And http://www.xmlplease.com/xhtml/xhtml5polyglot/

**Comment by Lausselloic** [comment]
Hello,

Thanks for the sample pages, I've fix the init for the V4 https://github.com/Orange-OpenSource/Orange-Confort-plus/tree/v4

We will update the master and browser extensions when thos release will be ready.
