### ISSUE TITLE
[Plugin Confort+] Arrêt

### ISSUE THREAD

**Issue by Valerieledunois** [Orange-OpenSource/Orange-Confort-plus#120]

**Comment by Valerieledunois** [comment]
au clique sur l'icône Confort+ dans la barre d'extension (icône Orange) :
Attendu :
- l'icône orange de la barre d'extension devient gris
- sauvegarde du mode d'usage en cours, 
- sauvegarde des réglages personnels de l'utilisateur
- si une palette est ouverte, la fermer, si l’icône confort+ est visible, l'enlever
- arrêter les réglages sur la page web.

**Comment by ffoodd** [comment]
Cette mécanique est en place ; il restera des ajustements sur le stockage des réglages mais nous n’avons pas encore les règles en question (doit-on écraser les précédents réglages stockés, par exemple ?).
