### ISSUE TITLE
[Palette Accueil] Ouverture

### ISSUE THREAD

**Issue by Valerieledunois** [Orange-OpenSource/Orange-Confort-plus#121]
Lorsque l'utilisateur clique sur l'icône Confort+ présent sur la page web, ouverture de #122 .
La palette Accueil s'affiche sur le bord droit de la page web (hors ascenseur), 
Dimensions de la palette Accueil : Hauteur 530 pixels Largeur 425 pixels
La palette Accueil reste fixe lorsque l'utilisateur se déplace avec les ascenseurs sur la page web.
Description du contenu de la palette Accueil #122 

<img width="384" alt="PositionPalette" src="https://github.com/Orange-OpenSource/Orange-Confort-plus/assets/131779027/8ea3efb9-aaf0-4117-b1b1-56760002c932">

**Comment by notabene** [comment]
⚠️  Si la palette reste fixe elle ne peut pas faire `530px` de haut mais au mieux, la hauteur du _viewport_ (la partie visible du navigateur), moins une dizaine de pixels en bas pour bien faire comprendre qu'elle est « finie » et qu'il ne reste rien sous le pli visible.

@ffoodd  ton avis ?

**Comment by ffoodd** [comment]
Les dimensions n’ont pas vraiment de sens de toute façon à ce stade : 

- sur un petit écran ce sera trop, sur un grand écran ce sera peu ;
- l’espace disponible (et donc qu’on peut utiliser raisonnablement) dépend du _viewport_ donc de la fenêtre ;
- le fait de fixer la palette est déjà délicat, une _issue_ est ouverte pour la version actuelle demandant de pouvoir choisir son emplacement (#68 : je l’avais ouverte mais c’était une demande reçue sur Twitter, à l’époque).

**Comment by notabene** [comment]
> * l’espace disponible (et donc qu’on peut utiliser raisonnablement) dépend du _viewport_ donc de la fenêtre ;

On est raccord 🙂 

> * le fait de fixer la palette est déjà délicat, une _issue_ est ouverte pour la version actuelle demandant de pouvoir choisir son emplacement ([Choose toolbar position and behaviour #68](https://github.com/Orange-OpenSource/Orange-Confort-plus/issues/68) : je l’avais ouverte mais c’était une demande reçue sur Twitter, à l’époque).

Notons qu'il s'agit aussi de s'appuyer sur une convention majoritairement répandue, ce n'est pas farfelu de la poser en haut à droite (cependant même si dans une version future on peut imaginer un mécanisme de bascule d'un côté à l'autre par exemple, mais ça complique encore l'interface et je serais bien incapable de juger de sa pertinence).

**Comment by ffoodd** [comment]
On peut considérer ce ticket comme clos, avec la nuance des dimensions qui ne sont pas implémentées de manière absolue : la palette fait `560px` de large et la hauteur de la fenêtre.

Ces dimensions pourront être ajustées au besoin, mais sur mon psote c’est clairement le minimum viable :

![image](https://github.com/Orange-OpenSource/Orange-Confort-plus/assets/2890570/b8e36d75-4b1b-489e-98fb-81ed194edf35)

**Comment by Valerieledunois** [comment]
Remarque des concepteurs suite à présentation de la palette : Il faut que les utilisateurs puissent bien distinguer que c'est un objet à part : il faut un cadre de palette qui tranche
merci
