### ISSUE TITLE
version 4.1.1 cannot initialize (no error)

### ISSUE THREAD

**Issue by Philalawst** [Orange-OpenSource/Orange-Confort-plus#130]
I can't initialize the confortplus

The library is loaded just before the `</body>` (I see it in the library are loaded cfr developper network tab on chrome)

I put  `<div id="confort-plus-container"></div>` in the html, before `<script src="/themes/custom/vivalia2025/assets/js/vendor/Orange-Confort-plus/dist/serveur/js/toolbar.js?v=10.1.1"></script>`.

I added these lines
```js
accessibilitytoolbar_custom = {
  idLinkModeContainer: 'confort-plus-container',  
  cssLinkModeClassName: 'btn-confort',
  idSkipLinkIdLinkMode: '',
  cssSkipLinkClassName: '',
};
```

the `<div id="confort-plus-container"></div>` stay empty.

I have no JS error in the console

I put a `console.log` in `accessibilitytoolbar.init` function and i see it.

**Comment by ffoodd** [comment]
Hi there,

Is there any 404 or 500 in your network tab?
Could you try without using a container, to check if that's something with this feature?

**Comment by Philalawst** [comment]
Hi,

I remove all, I started everything again and it's work...

I don't understand why, I was sure of what I had done -_-

sorry

**Comment by ffoodd** [comment]
Yoi're welcome, happy to know it works!
