### ISSUE TITLE
[Mode d'usage Vision+] Spécification des réglages

### ISSUE THREAD

**Issue by Valerieledunois** [Orange-OpenSource/Orange-Confort-plus#141]
![image](https://github.com/Orange-OpenSource/Orange-Confort-plus/assets/131779027/cb97e88b-d3ad-47f6-aa96-75082cf8a99b)

[VISION+.docx](https://github.com/Orange-OpenSource/Orange-Confort-plus/files/14806147/VISION%2B.docx)

La description du mode d'usage est dans le fichier word joint

**Comment by ffoodd** [comment]
## À faire

Certains réglages présents dans le mode Facile+ sont estimés sur le ticket dédié, #142. 
**Attention**, la valeur par défaut pour le mode d’usage peut varier !

### Règle de lecture (1)

- [ ] Ajouter la règle horizontale
- [ ] Revoir l’aspect du composant

### Marge (1)

- [ ] Créer le composant
- [ ] Implémenter les valeurs

**Question** : on a le détail de ce qu’est une « marge » ?

### Apparence des liens de navigation (8)

- [ ] Créer le composant
- [ ] Créer les différents réglages

**Note**: on va devoir gérer les adhérences entre les valeurs des différents réglages.

## Questions génériques

1. Les réglages multi-critères : comment fonctionnet-ils ? Les valeurs des sou-réglages sont dépendantes les unes des autres ? À quoi ça ressemble, visuellement ?
2. LEs réglages avec des valeurs numériques ou de couleur : quelle est la règle pour déterminer si l’utilisateur peut ajouter une valeur personnalisée ? Ce ne sera clairement pas dans le MVP.

**Comment by ThomasDgop** [comment]
# Màj après MVP:

## Questions et ajustements des réglages existants
- [ ] Pour la règle et le masque de lecture, faut-il ajouter un bouton pour désactiver le réglage en dehors de C+ ?
- [ ] Quelles valeurs pour la marge ?
