### ISSUE TITLE
Path-based XSS when using distant script

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Confort-plus#16]
Hi there,

While working on a project, security audit informed me about this: on a page calling `//SERVEUR/js/toolbar-min.js` (then requesting `http://SERVEUR/cookie.php`), adding script on request origin — like `example.com/?"><script>alert('check!');</script>` — will execute script in Comfort+ response…

In my example an alert will be displayed by `comfort.orange.com` on `example.com`.

The response contains the following:
```
  sendBackData();
  function sendBackData()
		{  
			if(window && window.parent && window.parent.postMessage)
			{
window.parent.postMessage('00006510006506506500000000000000000065000000000', 'http://example.com/?"><script>alert('check!');</script>');
			}
		}
    function redirect()
    {
      document.location.href="cookie2.php?origin=http://example.com/?"><script>alert('check!');</script>&hostname=example.com";
    }
```

I'll try to use a standalone version but maybe I did something wrong? Please let me know :)

**Comment by Lausselloic** [comment]
Thanks for this issue notification. 
Fix in the source code and serveur, remove document.location.href which also include query string, and replace it by location.protocol+'//'+location.hostname+location.pathname, by this way, query string is removed and this XSS is fixed
