### ISSUE TITLE
possibilité de configurer confort plus

### ISSUE THREAD

**Issue by goetsu** [Orange-OpenSource/Orange-Confort-plus#18]
Bonjour,

existe-t-il des paramètres de configuration permettant de désactiver certaines options ou d'avoir la toolbar ouverte par défaut ?

Merci

**Comment by Lausselloic** [comment]
Hello,

Today there's no configuration param to disable some option. If it's a standalone version hosted on your website, you can only comment some part of html code and attach event associated callback.

To open the toolbar by default, you can change the default cookie value in "app/cookie.html" and set the bit before the end to 1 like this : 
```
var defaultValuePref = '0000651000650650650000000000000000006500000010';
```
This will display the toolbar by default for each user who haven't any cookie at time.

Actual implementation "closed by default" is a design choice, to prevent displaying toolbar for those who don't care about it.

**Comment by sdeschamps-orange** [comment]
Closing if it's OK for you @goetsu + see #19 @Lausselloic has decided to take it into account more soundly.
Let us know if you've got any more trouble.

**Comment by goetsu** [comment]
ok for me thank
