### ISSUE TITLE
configuration option - allow to disable all option individually easily

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Confort-plus#19]
Following this question : https://github.com/Orange-OpenSource/Orange-Confort-plus/issues/18

Need to check howto propose a configuration input file allowing to quickly enable/disable option of the toolbar

**Comment by sdeschamps-orange** [comment]
An 'options' array similar to what's common to jQuery plugins, perhaps?

`this.defaults` / `this.options` sort of.

**Comment by Lausselloic** [comment]
yes, but also need to filter IHM component to remove disabled options, and event handlers...

Bu I keep the idea for a symple way of providing option in the initialization like actual ``` accessibilitytoolbar_custom ``` options

**Comment by ffoodd** [comment]
That's not something in the current v5 roadmap, so I'm going to close this as stale for now.
