### ISSUE TITLE
focus auto moved to "on/off" button after each option update

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Confort-plus#20]
By using keyboard or mouse to update option in advanced panel, after each update for example font-size normal -> big the focus is moved to "on/off" switch button.
-> Can be reproduced on the latest Chrome and Firefox official extension.
And also on the master branch code

**Comment by sdeschamps-orange** [comment]
(Cannot reproduce)

**Comment by Lausselloic** [comment]
fixed in 4.1.0
