### ISSUE TITLE
Dysfonctionnements Confort +

### ISSUE THREAD

**Issue by lesmediatheques35** [Orange-OpenSource/Orange-Confort-plus#21]
Bonjour, 

Utilisateurs de votre outil sur notre site (www.lesmediatheques-rennesmetropole.fr), nous constatons des dysfonctionnements depuis quelques semaines. En effet, deux options ne sont plus effectives, alors que l'outil fonctionnait encore intégralement récemment.

Les options ciblées sont l'agrandissement de la taille de la police ainsi  que la couleur du texte :

•	L'agrandissement de la taille de la police n'effectue plus aucun changement sur nos pages,

•	La bascule du texte en couleur vers le noir sur fond blanc fonctionne partiellement.

Nous souhaitons mettre en avant prochainement votre service dans un article dédié, mais nous ne pouvons actuellement assurer cette promotion si toutes les options ne sont pas à ce jour fonctionnelles.

Merci par avance pour votre retour,

**Comment by Lausselloic** [comment]
Bonjour,

En effet, je reproduis bien ces dysfonctionnements. 
Concernant l'agrandissement de la taille de police, celle-ci s'applique sur la balise HTML, et impose que toutes les polices exprimées dans la page soient en police relative. Le dysfonctionnement actuel vient d'une taille de police fixée à 14px sur le body : 
![image](https://user-images.githubusercontent.com/11272238/28068376-88aa32f6-6645-11e7-86c1-fed2d18805a1.png)

Concernant la bascule du texte, la définition d'une couleur d'arrière-plan surcharge les arrières plans transparents utilisés sur les liens du site 
```
a {
  background-color: transparent;
}
```
Notamment utilisé pour vos effets de survol des liens classe lien-hover. Nous n'avons de meilleure solution technique pour forcer les contrastes à ce jour.

Je vous invite également à mettre à jour la version du service disponible https://github.com/Orange-OpenSource/Orange-Confort-plus/releases/tag/4.1.0

**Comment by Lausselloic** [comment]
Je viens de mettre à jour le code source pour prendre en compte la définition d'une taille sur le body et non sur le tag html comme attendu initialement : https://github.com/Orange-OpenSource/Orange-Confort-plus/commit/6c6d8d33ac4420d1531304ea28c4b7256f4678cb

Je n'ai aucune solution fonctionnelle concernant la gestion des arrières plan transparent. La transparence est aussi supprimées lorsque l'utilisateur active l'option dans le panneau "+ de réglages -> agencement -> suppression des effets de transparence"

**Comment by lesmediatheques35** [comment]
Bonjour,

Merci beaucoup pour vos retours et votre réactivité.

Afin de bénéficier de la modification du code source, devons-nous effectuer la mise à jour de l'outil évoquée dans votre courriel du mardi 11 juillet dernier ?

Merci par avance et bonne journée,

Equipe portail
46, boulevard Magenta - CS 91231
35012 Rennes cedex
Tél : 02 23 40 66 90
Télécopie : 02 23 40 67 36
portail-mediatheques@rennesmetropole.fr<mailto:portail-mediatheques@rennesmetropole.fr>
[cid:image001.png@01D2FBC2.66E86860]



De : Laussel Loïc [mailto:notifications@github.com]
Envoyé : jeudi 13 juillet 2017 10:22
À : Orange-OpenSource/Orange-Confort-plus
Cc : Portail Médiathèques; Author
Objet : Re: [Orange-OpenSource/Orange-Confort-plus] Dysfonctionnements Confort + (#21)


Je viens de mettre à jour le code source pour prendre en compte la définition d'une taille sur le body et non sur le tag html comme attendu initialement : 6c6d8d3<https://github.com/Orange-OpenSource/Orange-Confort-plus/commit/6c6d8d33ac4420d1531304ea28c4b7256f4678cb>

Je n'ai aucune solution fonctionnelle concernant la gestion des arrières plan transparent. La transparence est aussi supprimées lorsque l'utilisateur active l'option dans le panneau "+ de réglages -> agencement -> suppression des effets de transparence"

**Comment by Lausselloic** [comment]
oui exactement, en récupérant la version présente dans le répertoire dist/serveur du commit, et en configurant hebergementDomaine et hebergementFullPath des fichiers toolbar.js et toolbar-min.js selon la configuration de votre instance pour conserver un hébergement local.

On en utilisant le fichier hébergé sur github directement dans votre portail : 
<script type="text/javascript" src="http://confort-plus.orange.com/js/toolbar-min.js"></script>

**Comment by lesmediatheques35** [comment]
Bonjour, 

Nous avons depuis notre dernier échange transmis l'ensemble des informations à notre prestataire web, et celui-ci nous remonte qu'il lui est impossible de remettre le service en place car il ne supporte pas le HTTPS...confirmez-vous ce souci?

**Comment by Lausselloic** [comment]
Bonjour,

Le service proposé en inclusion depuis l'url github n'est en effet pas en HTTPS.

Cependant si vous l'hébergez sur vos serveurs, celui-ci fonctionne en HTTPS, pour cela il suffit de configurer les variables dans le fichier toolbar.js ou toolbar.min.js présents dans le dossier dist de la version : 
var hebergementDomaine = 'https://MONDOMAINE';
var hebergementFullPath = hebergementDomaine + '/MONCHEMINDEDEPLOIEMENT/';

**Comment by Lausselloic** [comment]
Hello,

Je viens de basculer le service en HTTPS et je constate que vous avez réussi à héberger le service sur votre portail :-)

Je clôture cette issue
