### ISSUE TITLE
Étapes d'installation peu claires - Wordpress

### ISSUE THREAD

**Issue by felschrr** [Orange-OpenSource/Orange-Confort-plus#223]
Si possible rendre un peu plus clair les étapes d'installation dans le README, j'ai du scroll plusieurs discussions avant de comprendre qu'il fallait modifier la variable hebergementDomaine du fichier toolbar.js pour pouvoir afficher correctement la toolbar.

**Comment by ffoodd** [comment]
Merci pour le ticket, j’ai mis à jour le `README.md` pour éviter ce piège et ajouter quelques détails.
