### ISSUE TITLE
Failed to read named property 'contentDocument'

### ISSUE THREAD

**Issue by RavanH** [Orange-OpenSource/Orange-Confort-plus#231]
Hi, working the latest script into a dev site, I'm getting this error:
 
> DOMException: Failed to read a named property 'contentDocument' from 'Window': Blocked a frame with origin "https://dev.xxxxx.com" from accessing a cross-origin frame.
>     at Object.setCSS (https://dev.xxxxx.com/serveur/js/toolbar.min.js?ver=5:6:856366)
>     at Object.loadTheToolbar (https://dev.xxxxx.com/serveur/js/toolbar.min.js?ver=5:6:862932)
>     at Object.firstInitToolbar (https://dev.xxxxx.com/serveur/js/toolbar.min.js?ver=5:6:862778)
>     at init (https://dev.xxxxx.com/serveur/js/toolbar.min.js?ver=5:6:861798)

The toolbar works, but any script that is added after the toolbar.min.js, is failing...

This error occurs on Chrome 125.0.6422.141 (on Linux)

**Comment by ffoodd** [comment]
Hi there,
I removed one of three occurrences for `contentDocument` that was useless and ensured to log errors in the console when possible. 

However there's more chance that you're encountered [a Same-Origin issue](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) and there's nothing Confort+ can do with that. But it should not stop working in that case.

Please try the incoming commits on `main` to check if that helps.
