### ISSUE TITLE
Feature request: dynamic variables

### ISSUE THREAD

**Issue by RavanH** [Orange-OpenSource/Orange-Confort-plus#232]
Hi, working to work the Orange Confort plus script into a WordPress plugin (to be published on WordPress.org if you allow me) I would like to be able to assign certain variables like hebergementDomaine and hebergementFullPath in the root HTML. Editing the script file is not an option because these values depend on the site and WordPress installation.

A basic front-end integration, with dynamic variables, could look like this:

```
<script>
var hebergementDomaine = 'https://dev.status301.com'; // Your website origin, depending in site.
var hebergementFullPath = hebergementDomaine+'/wp-content/plugins/orangeconfortplus'; // Path to Confort+ folder, depending on WP install.
</script>
<script type="text/javascript" src="/wp-content/plugins/orangeconfortplus/js/toolbar.min.js?ver=123"></script>

```

To make this work, the main toolbar script would need some minor changes.

I would suggest to either NOT include the variable attributions for hebergementDomaine, hebergementFullPath, imagesPath, helpPath, uci_classic_toolbar_css and onOffEnabled in the main script at all, or allow them to be overwritten like this:

```
var hebergementDomaine = hebergementDomaine || window.location.origin;
var hebergementFullPath = hebergementFullPath || hebergementDomaine + '/';
var imagesPath = imagesPath || {
	arrows: hebergementFullPath + "img/arrows_60.png"
};
var helpPath = helpPath || {
	FR: hebergementFullPath + "help/help_fr.html",
	EN: hebergementFullPath + "help/help_en.html",
	ES: hebergementFullPath + "help/help_es.html",
	PL: hebergementFullPath + "help/help_pl.html"
};
var uci_classic_toolbar_css = uci_classic_toolbar_css || hebergementFullPath + 'css/classic-toolbar.css';
var onOffEnabled = onOffEnabled ?? true;
```

**Comment by ffoodd** [comment]
That's an easy fix so let's do it. 

However be aware that the current production release will not evolve anymore, as we're working on the next major release for months now.

Regarding embedding it in a WordPress plugin, you must conform to [GNU GPL v2.0](https://github.com/Orange-OpenSource/Orange-Confort-plus/blob/main/LICENSE) and you cannot use Orange's logo nor brand.

**Comment by RavanH** [comment]
> That's an easy fix so let's do it.

No need, if the new release is going to be so different anyway.

**Comment by ffoodd** [comment]
There are still tons of things to do with the next major (including documentation), so don't expect it before a few months…

That's why I'm trying some patches on the current release, if that can help in any case.

**Comment by RavanH** [comment]
Prefect. I'll be working with the current stable to start with then. I'll keep you posted :)
