### ISSUE TITLE
Failed to execute 'removeChild'

### ISSUE THREAD

**Issue by RavanH** [Orange-OpenSource/Orange-Confort-plus#236]
Hi, opening and then closing (hide) the toolbar script 4.3.3 embedded on a site, I get the following error.

> TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
>     at Object.setCSS (toolbar.js:6:860227)
>     at Object.loadTheToolbar (toolbar.js:6:879956)
>     at Object.reloadToolbar (toolbar.js:6:875901)
>     at Object.Annulation (toolbar.js:6:746055)
>     at HTMLButtonElement.<anonymous> (toolbar.js:6:834515)

I've not seen any broken toolbar functions however.

The weird thing is that while original script is called from `/wp-content/plugins/orange-confort-plus/vendor/js/toolbar.min.js`, the error is reported to be coming from a non-existent script file on `/wp-content/plugins/orange-confort-plus/vendor/js/dist/serveur/js/toolbar.js` (notice the added path and missing ".min")

The error is occurring in both Firefox 126 and  in Chrome 125 (on Linux), but I have not tested other browsers.

It can be seen live on https://dev.status301.com/ (open the toolbar, then close it again)

**Comment by ffoodd** [comment]
Regarding path, it's coming from the sourcemaps files. I don't know if it can be customized in our build, will check.

I'll have a look at this error, but only work on Confort+ a day a week, and that was yesterday — so don't expect a fix before a few days...

**Comment by RavanH** [comment]
@ffoodd no worries, it does not seem to break anything... In the meantime, I've finished the first version of the WordPress plugin and submitted it for review to the WordPress.org team. It may take up to a month but when published, I'll let you know :)

**Comment by RavanH** [comment]
@ffoodd excellent, I'll be testing soon :) ... In the meantime, I've published a basic (working) Orange Confort+ for WordPress plugin on https://github.com/RavanH/orange-confort-plus. I've not used the Orange logo but did include copies of the example images that are used on https://confort-plus.orange.com/. I also chose to use the full name 'Orange Confort+" in the plugin title. Please let me know if it is alright or not and I'll adapt asap!
