### ISSUE TITLE
Personnalisation du bouton

### ISSUE THREAD

**Issue by Spidlace** [Orange-OpenSource/Orange-Confort-plus#39]
Bonjour,

Chouette module d'accessibilité ! Bravo à vous.
Une petite question cependant, il y a t'il un moyen d'ajouter plus tard la personnalisation de l'emplacement du bouton ? Il s'ajoute par défaut en haut du body mais j'aurais aimé le mettre autre part.

Merci par avance,

**Comment by Lausselloic** [comment]
Bonjour,

Il est possible de remplacer le bouton par un mode "lien" comme décrit dans l'issue #38 Cela permet de modifier l'apparence et la position de celui-ci.

**Comment by Spidlace** [comment]
My bad !!
Merci, bien ;-)

**Comment by Lausselloic** [comment]
Pas de soucis, il faut que l'on améliore la documentation de cette option see #40

**Comment by Spidlace** [comment]
Du coup super pour ça, mais possible de changer le text "Confort +" dans le lien ?
J'ai cru voir que ça reprenait la variable "uci_serv_name" mais impossible de la surcharger 

`this.lien.textContent = this.get('uci_serv_name');` (l.6626 - toolbar.js)

**Comment by Lausselloic** [comment]
Oui en effet "Confort+" étant le nom du service, celui-ci n'est pas modifiable. Cela permet aux utilisateurs d'identifier rapidement le service lorsqu'il est présents sur les différents portail.

**Comment by Spidlace** [comment]
Ok ça marche, merci de la réponse.
