### ISSUE TITLE
Taille du texte

### ISSUE THREAD

**Issue by arupin** [Orange-OpenSource/Orange-Confort-plus#41]
Bonjour

Tout d'abord merci pour votre travail.

Nous sommes en cours d'intégration de votre outil dans notre portail (www.toutatice.fr).
Nous ne parvenons pas à faire fonctionner les changements de taille du texte (alors que CTRL+/- fonctionne bien). Le souci provient vraisemblablement de notre portail, aussi pouvez-vous nous rappeler le pré-requis pour pouvoir obtenir cette fonctionnalité svp ?

Merci

**Comment by Lausselloic** [comment]
Bonjour,

En effet l'agrandissement des caractères appliqué par Orange Confort+ est un agrandissement proportionnel de la taille initiale de la balise html;

Pour que cela fonctionne, il faut que toutes les tailles de polices soient exprimées dans une unité relative (rem, em, %) et non en px

Je constate que vous utilisez Bootstrap en version 3.x sur le portail. Celui-ci définit des tailles de police exprimées en px, à commencer par le body.

Vous pouvez soit passer sur Bootstrap 4, soit tester avec Boosted (3.3.3) qui est une surcouche de Bootstrap 3.x mais avec des unités relatives.

**Comment by arupin** [comment]
Bonjour

Merci beaucoup pour votre rapidité.
Le passage vers Bootstrap 4 est dans notre roadmap mais pas dans l'immédiat.

Comment pourrais-je, par exemple, ne pas afficher les augmentations/réductions de la taille du texte svp ?

**Comment by Lausselloic** [comment]
Mauvais idée de désactiver cette fonctionnalité.

Par contre passer en rem au lieu des PX ne semble pas très compliqué, sur la page d'accueil, en ajoutant dans la css du portail après Bootstrap : 

```
body{
font-size: .8125rem;
}
head {
font-size: 1rem;
}
.btn {
font-size: .8125rem;
}
```

Reste à identifier si d'autres surcharges de font-size sont nécessaires en jouant avec l'agrandissement de caractères.

**Comment by arupin** [comment]
Merci.
