### ISSUE TITLE
Installation sur Windows 7 32 bits, IE 11

### ISSUE THREAD

**Issue by Pibus** [Orange-OpenSource/Orange-Confort-plus#42]
Après installation sans erreur, l'icone apparaît bien dans la barre de commandes, le module est bien activé, mais Confort+ ne charge jamais dans la page.

release 4.2.0
9d30c49

**Comment by Lausselloic** [comment]
Bonjour Pibus,

Sur quelle(s) urls as-tu testé l'extension? Via la console de développement (F12) as-tu un message d'erreur dans la console?

Je n'ai pas de version 32 bits pour tester

**Comment by Pibus** [comment]
Bonjour Loïc,
J'ai :
> SCRIPT5007: Impossible d’obtenir la propriété  « replace » d’une référence null ou non définie
> Fichier : script block (11), ligne : 494, colonne : 9

Ce qui nous place à la dernière ligne de cet extrait :

```
/**
     * Create the string separate by | for cookie or localstorage save
     * format: websitedisable|currentprofilname|profilname1|valueprofil1|profilname2|valueprofil2 ....
     * 
     */
    this.decodeUsageConfort= function (storageValue) {
        var settings = storageValue.split('|');
         // need to explode the values
         // at least 4 entry : 
         // first bit set site enable or disable second set toolbar enable, third one set default lang, 4th one set to no profile
        // first param set site enable or disable
        var disablevalue = settings.shift();
        if(!onOffEnabled) disablevalue = 0;
        this.stackv3["a11ySiteWebEnabled"] = this.convertMatrixv3["a11ySiteWebEnabled" + "-" +disablevalue].replace(/.*-/, "");
        var a11yToolbarEnable = settings.shift();
        this.stackv3["a11yToolbarEnable"] = this.convertMatrixv3["a11yToolbarEnable" + "-" +a11yToolbarEnable].replace(/.*-/, "");

```

![image](https://user-images.githubusercontent.com/432169/37774002-5c743062-2ddf-11e8-9345-39766be5efd8.png)

**Comment by Lausselloic** [comment]
Hello,

Peux-tu me fournir l'url sur laquelle tu rencontre le soucis? et/ou me dire si tu rencontre le soucis sur le site https://boutique.orange.fr/ ?

Loïc

**Comment by Pibus** [comment]
Je teste sur la page https://www.google.fr
Même problème sur d'autres pages, dont https://boutique.orange.fr/

**Comment by Lausselloic** [comment]
La valeur du storagevalue est erronée. Je ne saurais expliquer pourquoi. Peux-tu aller voir dans le registre?

Dans le chemin : HKEY_USERS\S-XXXXXXXXX\Software\AppDataLow\Software\Orange.ConfortPlus.IEExtension il doit y avoir les valeurs du stockage (blacklist, enabled et UCI41) si celle-ci n'existent pas les créer avec les valeurs : 
blacklist -> vide
enabled -> 1
UCI41 -> 0|0|0

tu peux aussi effectuer une recherche dans le registre de la clé UCI41

Est-ce une première installation de l'extension? Ou une mise à jour de celle-ci?

**Comment by Pibus** [comment]
J’irai voir le registre et te posterai les détails.

Le plugin n’était pas présent avant installation, mais possible qu’une version précédente ait été installée puis desinstallée.

Cependant, j’ai fait un test avec la v4.1 : pas de problème. Je suis revenu à la 4.2, qui ne fonctionne toujours pas.

**Comment by Lausselloic** [comment]
La version 4.1 utilise comme clé de registre "userpref" pour mémoriser les préférences. cette clé à été modifiée pour la v4.2. 

J'espère que le problème est isolé et qu'il va se résoudre.

**Comment by Lausselloic** [comment]
Bonjour @Pibus le problème s'est-il reproduit? Peut-on clôre cette issue?
