### ISSUE TITLE
Langue par défaut

### ISSUE THREAD

**Issue by arupin** [Orange-OpenSource/Orange-Confort-plus#43]
Bonjour

Existe-t-il un moyen de changer la langue par défaut svp ?
EN -> FR par exemple.

Faut-il modifier locale ou defaultLocale dans toolbar.js ou est-il possible de faire l'équivalent  via accessibilitytoolbar_custom ?

Merci

**Comment by Lausselloic** [comment]
Hello,

Par défaut le service prend la langue déclaré dans la balise html du site (bonne pratique d'accessibilité). Si on souhaite forcer la langue par défaut il faut modifier les 2 valeurs : 

```
var defaultLocale = "FR";
    /**
     * A {String} force default locale language
     * @private
     */
    var ForceDefaultLocale = true;  // pour bypasser la détection du navigateur 
```
dans toolbar.js

**Comment by Lausselloic** [comment]
@arupin je considère que la réponse était correcte? Je clôture l'issue, à réouvrir si nécessaire.
