### ISSUE TITLE
custom max and min font size

### ISSUE THREAD

**Issue by narenbimal** [Orange-OpenSource/Orange-Confort-plus#44]
How we can provide custom values for maximum and minimum font size in confort+?

**Comment by Lausselloic** [comment]
Hello,

Could you explain what's the expected result, and what do you mean by "custom values" ?

Today font-size settings is a ratio based on the original website font-size. So I don't really understand what you want to achieve.

**Comment by Lausselloic** [comment]
I close this issue without more information, don't know what's expected
