### ISSUE TITLE
Les profils créées disparaissent après fermeture du navigateur

### ISSUE THREAD

**Issue by amezigh** [Orange-OpenSource/Orange-Confort-plus#45]
Bonjour,

Lorsque l'on crée et sauvegarde un ou plusieurs profils, ces derniers restent en mémoire tant que le navigateur reste ouvert. Il est possible de fermer la fenêtre, d'en ouvrir une autre et de les retrouver.

Cependant lorsque l'on ferme entièrement le navigateur, qu'il s'agisse de Chrome, Firefox, IE ou Edge, les profils ne sont plus retrouvables. 

Merci à vous !

**Comment by liyokuna** [comment]
Bonjour,

Ce problème est lié à la date d'expiration du cookies.
J'ai apporté la modification nécessaire. Un version (4.2.1) sera disponible sous peu.
-----------------

This issue is caused by the missing of expiration date.
It's now fixed.  I will release another version soon (4.2.1).

**Comment by amezigh** [comment]
Merci pour votre réactivité et la mise à jour !
