### ISSUE TITLE
installer orange confort plus

### ISSUE THREAD

**Issue by melanie-hdvl** [Orange-OpenSource/Orange-Confort-plus#46]
Bonjour, j'ai bien regardé les explications, mais je butte sur l'installation. J'ai bien vu les fichiers dist/serveur/js/toolbar.js  et  dist/serveur/toolbar-min.js et j'ai compris comment les modifier. Mais il me manque l'essentiel : les fichiers de base.
Chez mon hébergeur j'ai créé un dossier confort-plus, je voudrais y installer les fichiers nécessaires, mais je ne ais où les trouver. J'ai cliqué sur dis/serveur et j'ai fait : enregistrer la cible du lien sous. Cela me donne un fichier "serveur" dans mon dossier Téléchargements. Mais ensuite ?
Pouvez-vous m'aider s'il vous plaît ? Merci

**Comment by melanie-hdvl** [comment]
Je crois que j'ai trouvé quelque chose, il fallait aller là :
https://github.com/Orange-OpenSource/Orange-Confort-plus#bugs-and-feature-requests
j'ai cliqué sur download. Cela m'a donné : Orange-Confort-plus-master.zip que j'ai dézippé. Et j'ai expédié le contenu dans mon dossier confort-plus, c'est à dire : app, dist, docs et le reste.
Est-ce bien cela ??

**Comment by melanie-hdvl** [comment]
Merci de me répondre ainsi, mais les dossiers msi ne me conviennent pas car je suis sous linux.
C'est seulement le contenu du doosier dist/serveur qu'il faut mettre chez l'hébergeur ?

**Comment by melanie-hdvl** [comment]
J'ai "closed" ce message par erreur. Comment faire pour le remetre en actif ? Merci

**Comment by melanie-hdvl** [comment]
Excusez-moi, je reviens vers vous, je ne suis pas développeuse, je suis seulement pifo-bidouilleuse. .Et je ne parle pas l'anglais. Pour autant je m'occupe du site accessdvlinux.fr. Cheze l'hébergeur j'ai créé le dossier confortplus à la racine, et j'ai placé dedans le contenu de dist/serveur.
J'ai modifié le fichier toolbar.js et j'y ai mis :1st_place_medal: est-ce bon ?mais je ne vois pas comment modifier le fichier: 
/* orange-confort-plus - version 4.1.0 - 24-11-2017
enhance user experience on websites
 Copyright (C) 2014 - 2017 Orange */
var hebergementDomaine = 'http://accessdvlinux.fr';
var hebergementFullPath = hebergementDomaine + 'http://accessdvlinux.fr/confortplus';
// Source: app/conf/hebergement.js
/*
Est-ce bon ? Mais je ne vois pas comment modifier le fichier /toolbar-min.js  il y a trop de lignes !

**Comment by Lausselloic** [comment]
re, alors non pour le path ce serait plutot : 
var hebergementDomaine = 'http://accessdvlinux.fr';
hebergementDomaine + '/confortplus/';

Pour ce qui est de la version toolbar.min pas il n'est pas obligatoire de le modifier, il suffit d'utiliser le toolbar.js depuis vos pages web dans l'import : 

<script type="text/javascript" src="http://accessdvlinux.fr/confortplus/js/toolbar-min.js"></script>

**Comment by melanie-hdvl** [comment]
avec ceci ça ne fonctionne pas.
<script type="text/javascript" src="http://accessdvlinux.fr/confortplus/js/toolbar-min.js"></script>
Ne fallait-il pas :+1:
<script type="text/javascript" src="http://accessdvlinux.fr/confortplus/js/toolbar.js"></script>
mais ça ne va pas non plus.

J'ai regardé ailleurs et eux ils fonctionnent : 
<script type="text/javascript" src="http://www.bnfa.fr/app/confort-plus/js/toolbar-min-fr.js"></script>
mais je sens qu'on approche du but !

**Comment by Lausselloic** [comment]
Hello yes j'ai répondu trop vite :-)
<script type="text/javascript" src="http://accessdvlinux.fr/confortplus/js/toolbar.js"></script> 

En ayant bien modifié
var hebergementDomaine = 'http://accessdvlinux.fr';
var hebergementFullPath = hebergementDomaine + '/confortplus/';

dans le fichier

**Comment by melanie-hdvl** [comment]
Je vous remercie, la ligne magique est bien celle-ci.
<script type="text/javascript" src="https://accessdvlinux.fr/confortplus/js/toolbar.js"></script>

j'ai fabriqué un fichier html comme ceci :

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<title>Orange Confort Plus</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="generator" content="Geany 1.24.1" />
</head>

<body>
	<script type="text/javascript" src="https://accessdvlinux.fr/confortplus/js/toolbar.js"></script>
</body>
</html>


Ce fichier, je l'ai nommé : confort.html   et envoyé à la racine du site

Je suis allée  ici : https://addons.mozilla.org/fr/firefox/addon/orange-confort/ 

et ai cliqué sur : ajouter à Firefox.  Alors il y a un module complémentaire dans Firefox, nommé : Orange-Confort +      et une petite icône grise au tableau de bord, **pas facile à atteindre avec la souris**,quand on est  mal-voyant.

J'ai fait ceci : https://accessdvlinux.fr/confort.html et ai placé  « confort » en marque-page. 

J'ai lancé Firefox, et fait Alt + M et suis descendue  sur le marque-pages "confort", il y a alors un bouton en haut à droite, "confort plus", on peut facilement cliquer dessus. Ou bien tabuler jusqu’à entendre : confort-plus bouton,

Si on ouvre n'importe quel site internet, alors "confort+" permet de faire des réglages. On peut enregistrer ces réglages. 

Quand on  ferme internet, et qu’on le relance et qu’on ouvre n'importe quel site internet, le bouton est toujours là et les réglages précédents sont conservés.   
C'est vraiment un outil très pratique.
Merci de votre aide !

**Comment by Lausselloic** [comment]
Merci pour ce retour. Ravi que l'outil plaise, on est preneur de propositions d'amélioration de la solution si vous identifiez des point gênants.

**Comment by melanie-hdvl** [comment]
Merci, ce qui manque c'est un raccourci-clavier pour permettre aux mal-voyants de lancer l'outil. En effet l'icône au tableau de bord est trop petite et inaccessible au clavier.
Bonne continuation ! 
Vous avez peut-être vu que notre site https://accessdvlinux.fr est consacré à une distribution linux spécialement adaptée aux personnes mal-voyantes et aveugles.

**Comment by melanie-hdvl** [comment]
Bonsoir, finalement, après des essais répétés, le raccourci clavier manque énomément !
Espérons que vous pourrez le mettre en place bientôt !

**Comment by melanie-hdvl** [comment]
Merci, j'attendrai que cela fonctionne pour Firefox.
