### ISSUE TITLE
Installation de la toolbar en local

### ISSUE THREAD

**Issue by amezigh** [Orange-OpenSource/Orange-Confort-plus#48]
Bonjour,

J'essaie d'installer la toolbar sur un site WordPress vierge. Pour cela, j'ai modifié dans le fichier "toolbar.js"  (du dossier dist/serveur/js) les variables "hebergementDomaine" et "hebergementFullPath" : 
``var hebergementDomaine = 'http://localhost/confort-plus';``
``var hebergementFullPath = hebergementDomaine + '/wp-content/themes/confort-plus/';``

Le fichier "toolbar.js" est bien chargé et l'iframe pour le cookie est bien créé. Cependant les CSS et les images ne sont pas appelés, alors qu'ils sont placés dans le bon répertoire ("/wp-content/themes/confort-plus/images", "/wp-content/themes/confort-plus/css"), aussi le bouton "Confort +" n’apparaît pas. 
Les dossiers contenant les assets de la toolbar ont les droits d'écriture nécessaires et il n'y a pas d'erreur dans la console du navigateur, je ne vois donc vraiment pas d'où peut venir le soucis...

Je vous remercie !

**Comment by notabene** [comment]
Bonjour @amezigh - est-ce que tu peux vérifier les droits dans le dossier `/wp-content/themes/confort-plus/` pour commencer ?

**Comment by notabene** [comment]
(et ses sous-dossiers)

**Comment by amezigh** [comment]
Bonjour, 

Merci pour votre réponse. 

Les droits de lecture sont bien activés sur ces différents (sous-)dossiers, pour tous les types d'utilisateurs.

**Comment by Lausselloic** [comment]
Hello,

Est-ce que http://localhost/confort-plus/wp-content/themes/confort-plus/css/classic-toolbar.4669a29c.css répond?

Loïc

**Comment by Lausselloic** [comment]
peut-être lié à la dépose d'un cookie sur localhost qui est un domaine non valide. 

Peux-tu tester en enlevant le domain dans cookie.html : 
```
document.cookie = name+"="+value+"; expires="+expires+";domain="+document.location.hostname+"; path=/";
```
A remplacer par : 
```
document.cookie = name+"="+value+"; expires="+expires+"; path=/";
```

**Comment by amezigh** [comment]
Cela n'a rien changé. Pour info, je ne sais pas si cela est pertinent mais le script "toolbar.js" reste bloqué à la fonction init() à la ligne 8009, exécutée à l'infini, hormis si on commente la ligne `return;` à la ligne 8032 : 

```
  init: function () {
  [...]
    // Bypass the default toolbar theme
    // Check if user preference has finished loading
    if (!accessibilitytoolbar.userPref.isUserPrefLoaded()) {
      setTimeout(accessibilitytoolbar.init, "100");
      //return;
    }
```

**Comment by Lausselloic** [comment]
oui ça me parle :-) d'où la piste du problème qui m'attire vers un pb de récupération/génération du cookie.
Tant que le cookie ne peut pas être déposé et lu, le service ne démarre pas.

Est-ce qu'il n'y a pas un cookie sur le domaine? Sur quel navigateur es-tu?

**Comment by amezigh** [comment]
Rectification : Sur Firefox, la date d'expiration est correcte : `Tue, 27 Apr 2032 13:30:06 GMT`, mais le problème apparaît toujours ! :-D

**Comment by notabene** [comment]
Ping @liyokuna est-ce que https://github.com/Orange-OpenSource/Orange-Confort-plus/commit/cf9e00c665fe4bfa25ab2159f692d8dbe908a481 peut être en cause ?

**Comment by liyokuna** [comment]
ça m'étonnerait @notabene mais je vais regarder ça plus en détails

**Comment by liyokuna** [comment]
Hello @amezigh ,

J'ai poussé une modification, je pense que c'est bon :).

Cdt

**Comment by amezigh** [comment]
Bonjour @liyokuna , merci pour la modification, mais cela n'a pas eu d'impact sur la génération des cookies.

Cordialement

**Comment by liyokuna** [comment]
Pouvez vous me donner les caractéristiques de votre environnement de dev ( worpres version, etc...) je vais essayer de reproduire le problème de mon côté.

**Comment by amezigh** [comment]
J'ai reproduit le soucis en partant d'un site from scratch sur un serveur local (Wamp), avec une simple page HTML, le <body> contenant juste le code pour charger "toolbar.js" : 
```
<html>
[...]
<body>
  <script src="js/toolbar.js"></script>
</body>
</html>
```
Voici le code modifié dans le fichier `toolbar.js` : 
`var hebergementDomaine = 'http://localhost/scratch-confort-plus';
var hebergementFullPath = hebergementDomaine + '/';`

Les dossiers "css", "js", "fonts", "help" et "images" sont placés à la racine du projet. 

Cordialement

**Comment by liyokuna** [comment]
Bonjour @amezigh,

J'ai réussi à reproduire le problème, et à le résoudre sur wamp.
J'ai crée un dossier `/test` dans le dossier `www` et dans le fichier tooblar.js
j'ai renseigné ceci ```
var hebergementDomaine = 'http://localhost:8383';
var hebergementFullPath = hebergementDomaine + '/test/';
```
et ça a permis d'afficher la barre d'outils confort +.
Peux tu ressayer en suivant cette démarche et me dire si ça marche de ton côté.

Cdt

**Comment by liyokuna** [comment]
Bonjour @amezigh

Mon aide a-t-il résolu votre problème ?

Cdt

**Comment by amezigh** [comment]
Bonjour @liyokuna , 

Désolé pour ma réponse tardive. Le problème venait effectivement de là, j'aurais dû y penser plus tôt...

Merci pour vos réponses. 

Cordialement
