### ISSUE TITLE
ShortCut usability/a11y tests

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Confort-plus#49]
@liyokuna 

- change text: Edit the keyboard shortcut value --> Keyboard shortcut value

- the button to choose the key: `<button class="ucibtn ucibtn-sm ucibtn-secondary uci_bton_menu cdu_c uci_dropdown" aria-haspopup="true" aria-expanded="false" id="uci_shortcut_menu_button" type="button">Q</button> `, you must add:

1. an `aria-labelledby` pointing on the id of html element containing "keyboard shortcut value" and add the chosen key in this text (like "keyboard shortcut value (currently Q)") and this key value must be dynamic (user choice)
1. an `title` attribute, with exactly the same text as for the `aria-labelledby` (like "keyboard shortcut value (currently Q)")
- don't forget to modify the submenu nav 
Good luck !

**Comment by liyokuna** [comment]
#47
