### ISSUE TITLE
lien vers le script

### ISSUE THREAD

**Issue by melanie-hdvl** [Orange-OpenSource/Orange-Confort-plus#50]
Bonjour, je reviens vers la discussion#39 où il est écrit ceci :+1: 

<script type="text/javascript">
accessibilitytoolbar_custom = {
// MANDATORY : ID of the target container which will include the link. If not null, activate the display in link mode. The link will be added as the last element of the target container. idLinkModeContainer : "id_target_container",

 // OPTIONAL (put it as comments if useless) CSS class applied on the link to unify its appearance with the site.
cssLinkModeClassName : "linkClass",
 
// OPTIONAL (put it as comments if useless) When the service is displayed as a link in the page, a skip link is automatically added at the top of the page. If you already have a group of skip links, you can specify the target container where the skip link will be added. The link will be added as the last element of the target container. 
//idSkipLinkIdLinkMode : "", 

// OPTIONAL (put it as comments if useless) CSS class applied on the skip link
//cssSkipLinkClassName : "" 
};
</script>

Je ne sais pas comment l'utiliser. Mon script à moi est :+1: 
 <script type="text/javascript" src="http://aciah.accessdvlinux.fr/confortplus/js/toolbar.js"></script> 	

comment faire pour avoir un lien à peu près comme ça :+1: <a href=je-ne-sais-quoi>confort+</a>
je vous rappelle que je ne suis que pifo-bidouilleuse mais je voudrais bien y arriver quand même.
Ce lien, avec une tabulation, permettrait d'atteindre Confot+ sans utiliser la souris.
merci

**Comment by liyokuna** [comment]
Bonjour,

Pour avoir un lien de page, il suffit de spécifier l'id du container parent comme suite:
<script type="text/javascript">
accessibilitytoolbar_custom = {
idLinkModeContainer : "cplus",}; </script>
<script type="text/javascript" src="http://aciah.accessdvlinux.fr/confortplus/js/toolbar.js"></script> 
respectez bien l'ordre et si il y a déjà un groupe de lien sur votre portail, il suffit de spécifier le l'id du contenair parent.
Dans cet exemple, le contenair parent a pour id:cplus et ça peut être un tag comme div.

**Comment by melanie-hdvl** [comment]
Merci j'ai bien compris pour ces deux lignes-là :-1: 
<script type="text/javascript"> accessibilitytoolbar_custom = { idLinkModeContainer : "cplus",}; </script> <script type="text/javascript" src="http://aciah.accessdvlinux.fr/confortplus/js/toolbar.js"></script> 
mais que faut-il en faire ensuite ? On les place où ? on y rajoute quelque chose ?
Merci

**Comment by liyokuna** [comment]
lié à ma réponse #51 
Faites bien attention à ce que votre l'id du idLinkModeContainer soit bien présent sur une balise html.

**Comment by liyokuna** [comment]
#51
