### ISSUE TITLE
Invisible

### ISSUE THREAD

**Issue by melanie-hdvl** [Orange-OpenSource/Orange-Confort-plus#51]
Bonjour, j'ai mis Confort plus sur mon site mais il y a deux personnes qui disen t ne pas le voir, alors que je le vois, moi. Que peut-il se passer ?  Voir le site ici : aciah.accessdvlinux.fr
merci !

**Comment by liyokuna** [comment]
Bonjour,

Oui effectivement, on ne le voit pas. Il y a une erreur qui est retourné sur votre site en allant sur la console. ( Chrome)
Il faut le mettre le script juste avant la balise de fin du _body_.

```
<script type="text/javascript" src="js/toolbar-min.js"></script>
</body>
```

**Comment by melanie-hdvl** [comment]
Hello, vous aviez écrit de mettre le script où on voulait ....
Bon, cette fois je l'ai mis juste avant </body> Est-ce qu'on le voit maintenant ?

**Comment by liyokuna** [comment]
Sur votre code source html, il y a trois appel à la toolbar de confort plus.
le premier est dans le _head_, deux autres dans la _`div class="navigation-haut"`_.
et je ne le vois pas avant la balise de fin du _body_ ...
Un seum appel à Confort plus avant la balise de fin du body suffit largement.

Par exemple:
Vous avez une div qui contient des liens `<div class="cadre_G">`  à cette div ajoutez l'attribut `id` ( par exemple id=cplus ) et cette id servira à ajouter Confort + en dernière position dans cette div.

**Comment by melanie-hdvl** [comment]
Merci pour ces précieuses indications. J'ai finalement mis : 
<script type="text/javascript"> accessibilitytoolbar_custom = { idLinkModeContainer : "cplus",}; </script> 
<script type="text/javascript" src="http://aciah.accessdvlinux.fr/confortplus/js/toolbar.js"></script> 	   
juste avant </body>  ......... même si cela ne semble pas être le cas quand on regarde le code source
et j'ai ajouté :  <div class="cadre_GC" id="cplus"> </div>` 
et cette fois je crois que ça va ! Dites-moi ! Merci.

**Comment by liyokuna** [comment]
Génial !
Mais ça n'affiche pas. En débuggant, lorsque vous vous mettez au niveau du réseau, il y a un erreur d'appel à un fichier important du Confort plus.
Votre site est en HTTP et non HTTPS comme on peut le voir dans toolbar.js.
Changez sa valeur.

**Comment by liyokuna** [comment]
Bonjour @melanie-hdvl 
Avez vous pu résoudre le problème ?

**Comment by melanie-hdvl** [comment]
Non, c'est pas "closed" mais j'ai plein de soucis en ce moment et pas le temps de m'y remettre. Mais je trouve que c'est bien compliqué donc pas facile à adopter par quelqu'un 'de base' comme moi. Et on n'a pas tous les moyens de faire appel à un bon technicien.... qu'en plus faudrait trouver.
Donc, à une autre fois, je reviendrai.

**Comment by liyokuna** [comment]
D'accord, avec vos retours, j'ai pu amélioré la documentation (ajout d'information manquant, précision). Si vous vous y remettiez, n'hésitez pas à nous solliciter.

**Comment by melanie-hdvl** [comment]
Bonjour, je continue à regarder ce que vous faites, cr votre proposition est intéressante et serait formidable si elle offrait une option utilisable facilement pour tous les sites web, sans qu'il y ait besoin d'installer un script. Je voudrais une extension Firefox qui donnerait confort+. 
Dans l'immédiat j'ai découvert un plugin, userway, très facile à installer, car il y a un seul script à placer. Je l'a installé déjà dans trois sites et un forum.
Encore une fois votre confort+ m'intéresse aussi ... s'il y avait un addon à Firefox.
Bien cordialement à vous.

**Comment by liyokuna** [comment]
Bonjour, 
Nous avons des extensions sur [Chrome](https://chrome.google.com/webstore/detail/orange-confort%2B/ddnpdohiipephjpdpohikkamhdikbldp?hl=en), [Mozilla](https://addons.mozilla.org/fr/firefox/addon/orange-confort/?src=search) et IE.
On va essayer d'alléger et de simplifier le process.
Cordialement

**Comment by melanie-hdvl** [comment]
Allez, je vous ennuie encore !
Oui j'ai enfin trouvé votre extension pour Firefox et je l'ai installée, mais cela donne une petite icône au tableau de bord qu'on doit activer à la souris. De même qu'on doit activer à la souris le bouton qui ouvre la palette des réglages. Dans celle-ci on trouve, enfin, des raccourcis clavier ! S'il y en avait depuis le début ce serait super !
Cordialement
BP

**Comment by liyokuna** [comment]
Vous pouvez vous déplacer normalement sans la souris en utilisant les touches directionnelles du clavier et ou de la touche de tabulation.
https://github.com/Orange-OpenSource/Orange-Confort-plus/issues/49
