### ISSUE TITLE
Adding analytics

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Confort-plus#52]
Adding Google analytics into C+.

**Comment by juliemoynat** [comment]
Please, don't forget to ask for users' consent before activating Google Analytics in order to conform GDPR rules and respect users ;-)
Here is an article from CNIL (in French) about the subject: https://www.cnil.fr/fr/solutions-pour-les-cookies-de-mesure-daudience

Thanks

**Comment by liyokuna** [comment]
Thanks @juliemoynat.
yes of course, we can't miss the fact users consent is a top priority.
