### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by sihamscoopcom** [Orange-OpenSource/Orange-Confort-plus#55]
i got the following error on my console when deploying Confort+ on my website and the website doesn't show anything

toolbar-min.js:4 Uncaught TypeError: Cannot read property 'appendChild' of undefined
at new UciStorage (toolbar-min.js:4)
at Object.start (toolbar-min.js:20)
at toolbar-min.js:20 

PS: I'v inserted toolbar-min.js file in functions.php of my child theme like this : 

```
function my_theme_scripts_function() {
    wp_enqueue_script( 'myscript', get_stylesheet_directory_uri().'/myconfortplus/js/toolbar-min.js');
}
add_action('wp_enqueue_scripts','my_theme_scripts_function');
```

**Comment by liyokuna** [comment]
Hello there @sihamscoopcom ,

Can you tell me which browsers do you use ?

**Comment by Lausselloic** [comment]
Hello @sihamscoopcom,

Did you configure for your website?
```
var hebergementDomaine = 'http://confort-plus.orange.com';
var hebergementFullPath = hebergementDomaine + '/';
```

But that's not the point throwing the error I think, Orange Confort+ try to attach 2 node in the page in the body, first one is an iframe to retrieve cookie value, and if it's a success attaching the toolbar itself.

Looks like the error come from the iframe creation, could you try with the unminified version of toolbar?
And check if body tag exist in the page when script start?

**Comment by sihamscoopcom** [comment]
Thank you for reply, in fact the problem is resolved now, i had just to add
the HTML files to myconfortplus folder.

>
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
