### ISSUE TITLE
Adding the Luciole typeface

### ISSUE THREAD

**Issue by juliemoynat** [Orange-OpenSource/Orange-Confort-plus#56]
Hi,

Did you heard about the [Luciole typeface](http://www.luciole-vision.com/) designed specifically for visually impaired people?

This typeface considerably improves the readability of the text and is also appreciated by some dyslexic people (or non dyslexic too!). It could be very useful to add it to the possible typefaces in the Confort+ toolbar.

What do you think?

Thank you

**Comment by notabene** [comment]
+1

**Comment by Lausselloic** [comment]
Why not, we could replace actual options by a select option.

But before, I need to know what's the license of that font? Could we distribute it in our GPL project?

Can't find explicit licence other than the copyright at the bottom of the page : Luciole © Laurent Bourcellier & Jonathan Perez. 2019

**Comment by PigeardSylvain** [comment]
Thank you Loic !
