### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by Calilune** [Orange-OpenSource/Orange-Confort-plus#63]
Bonjour,
Je suis en train de créer un site avec le thème DIVI (wordpress). Je souhaiterais utiliser Orange Confort + mais je ne suis pas développeur.
J'aimerais savoir s'il existe un plugin Orange confort+ qui me permettrait d'en disposer sur mon site.
D'avance merci pour votre réponse,
Cordialement

**Comment by liyokuna** [comment]
Bonjour,

Nous avons pas de plugin wordpress pour Orange C+.
Vous pouvez utiliser ce [guide ](https://github.com/Orange-OpenSource/Orange-Confort-plus#deploying-orange-confort-on-your-website).

cdt

**Comment by Calilune** [comment]
Bonjour,
J'ai bien vu le guide mais j'avoue que je n'y comprends pas grand chose. Vous serait-il possible de me faire savoir où je dois positionner ce code afin que Orange confort + puisse fonctionner sur le site que je suis en train de créer.
Je sais me servir de Divi mais en ce qui concerne le code, pour moi, c'est le grand néant.
D'avance merci pour votre aide,
Cordialement

**Comment by Calilune** [comment]
Bonjour,
J'ai fermé la discussion par erreur.
J'ai bien vu le guide mais je n'y connais rien en code. Vous serait-il possible de m'aider afin que je puisse utiliser Orange confort + sur mon site.
D'avance merci
Cordialement

**Comment by Lausselloic** [comment]
Bonjour,

Pour permettre la mise à jour automatique de Confort+ nous préconisons l'utilisation de l'extension disponible pour Chrome, Firefox et IE11. Il est possible de proposer aux utilisateurs de l'installer afin d'en bénéficier sur tous les portails. 
Exemple de lien proposant aux utilisateurs d'installer le service : https://boutique.orange.fr/informations/accessibilite-autonomie/

Si vous souhaitez quand même l'intégrer en tant que service sur votre portail il faut : 
1. Télécharger Confort+ : https://github.com/Orange-OpenSource/Orange-Confort-plus/archive/4.2.1.zip
2. Déployer les fichiers contenu dans `dist/serveur/` avec les fichiers de votre portail, dans le dossier public
3. Modifier le fichier dist/serveur/js/toolbar.js pour définir les valeurs hebergementDomaine  et hebergementFullPath comme indiqué ici : https://github.com/Orange-OpenSource/Orange-Confort-plus#deploying-orange-confort-on-your-website
4. Dans les pages du portail ajouter le chargement du script Orange Confort + comme suit : <script type="text/javascript" src="https://monsiteweb.com/monchemindedeploiement/js/toolbar.js"></script>

**Comment by Lausselloic** [comment]
Hello @Calilune 

Avez-vous réussi à intégrer le service sur votre portail?

**Comment by Calilune** [comment]
Bonjour,
Merci pour votre dernier message. Comme je n'y connais rien, je pense que je vais recourir à un plugin Wordpress pour l'accessibilité.
Dommage car votre service me paraissait intéressant même si je me posais des questions concernant la mise à jour au regard de ce que vous m'avez écrit.
Encore merci pour vos réponses,
Cordialement



Envoyé de mon Galaxy model_name Orange

-------- Message d'origine --------
De : Laussel Loïc <notifications@github.com>
Date : 08/08/2019 16:06 (GMT+01:00)
À : Orange-OpenSource/Orange-Confort-plus <Orange-Confort-plus@noreply.github.com>
Cc : Calilune <martine.canonet@live.fr>, Mention <mention@noreply.github.com>
Objet : Re: [Orange-OpenSource/Orange-Confort-plus] Plugin (#63)


Hello @Calilune<https://github.com/Calilune>

Avez-vous réussi à intégrer le service sur votre portail?

**Comment by Avelornes** [comment]
> Bonjour,
> 
> Pour permettre la mise à jour automatique de Confort+ nous préconisons l'utilisation de l'extension disponible pour Chrome, Firefox et IE11. Il est possible de proposer aux utilisateurs de l'installer afin d'en bénéficier sur tous les portails.
> Exemple de lien proposant aux utilisateurs d'installer le service : https://boutique.orange.fr/informations/accessibilite-autonomie/
> 
> Si vous souhaitez quand même l'intégrer en tant que service sur votre portail il faut :
> 
> 1. Télécharger Confort+ : https://github.com/Orange-OpenSource/Orange-Confort-plus/archive/4.2.1.zip
> 2. Déployer les fichiers contenu dans `dist/serveur/` avec les fichiers de votre portail, dans le dossier public
> 3. Modifier le fichier dist/serveur/js/toolbar.js pour définir les valeurs hebergementDomaine  et hebergementFullPath comme indiqué ici : https://github.com/Orange-OpenSource/Orange-Confort-plus#deploying-orange-confort-on-your-website
> 4. Dans les pages du portail ajouter le chargement du script Orange Confort + comme suit : <script type="text/javascript" src="https://monsiteweb.com/monchemindedeploiement/js/toolbar.js"></script>

Bonjour, j'ai suivi cette explication, mais le bouton Confort n'apparaît pas. J'ai créé un site sur wordpress, j'ai mis le contenu du dossier dist/serveur dans le dossier /wp-content. J'ai modifié les fichier toolbar.js et toolbar.min.js comme indiqué dans le readme.md. J'ai appelé le script dans mon footer, avant la fermeture de la balise </body> en remplaçant bien l'url par la mienne. 
L'iframe est bien retrouvée quand j'inspecte l'élément, mais en bas du site, en 0px par 0px. Est-ce qu'il manque quelque chose pour que le bouton s'affiche correctement ?

**Comment by Avelornes** [comment]
Ok donc j'ai compris d'où vient le problème : 

Le Readme.md invite à appeler le script de cette manière : 

> You can call it anywhere on your website, just by adding the Javascript link, before the closing body tag, </body>, in your pages like this:

<script type="text/javascript" src="http://myexemple.com/myconfortplus/js/toolbar-min.js"></script>

Or, c'est le toolbar.js qui doit être appelé. De fait, avec cette modification, l'outil fonctionne sous wordpress.

**Comment by Lausselloic** [comment]
Hello,

Oui en complément du commentaire précédent qui indiquait qu'il fallait modifier le hebergementDomaine et hebergementFullPath dans toolbar.js, si on souhait utiliser la version minifiée en production, il faut également changer ces valeurs dans le fichier toolbar.min.js
