### ISSUE TITLE
erreur 406

### ISSUE THREAD

**Issue by bureau2crea** [Orange-OpenSource/Orange-Confort-plus#66]
Bonjour,

J'essaie d'installer "Orange Confort Plus" sur un site WordPress, mais cela ne fonctionne pas. J'ai bien effectué les étapes suivantes :
1 - Transférer le contenu du dossier "dist/serveur" dans un dossier interne à mon site internet "myconfortplus".
2 - Modifier "hebergementDomaine" et "hebergementFullPath"
3 - Créer le lien "<script>" vers le fichier "toolbar.js.

Le lien est fonctionnel, mais le bouton ne s'affiche pas. A la place, dans l'inspecteur Web de Chrome, cela m'affiche une erreur "406 (Not Acceptable)", pour la ligne 700 du fichier "toolbar.js" : document.getElementsByTagName('body')[0].appendChild(oNewNode);

Pouvez-vous m'éclairer ?

Cordialement,

**Comment by bureau2crea** [comment]
Quelques infos supplémentaires suite à des recherches. En effet, le fichier "cookies.html" affiche "Error" à cause de l'adresse du site. Celui-ci est contenu dans un sous-dossier (ex.: http://www.monsite.tld/site/).
Voici ce que me dit l'inspecteur web le fichier cookie.html :
cookie.html?hostname=www.monsite.tld&origin=http://www.monsite.tld/site/

**Comment by bureau2crea** [comment]
Bonjour. J'ai effectué une modification du nom de domaine pour éviter l'utilisation d'un sous-dossier pour accéder au site. Je passe d'une erreur 406 à une erreur 404.

Voici l'adresse générée et cela m'affiche la page 404 de wordpress :
_http://www.site.monsite.tld/wp-content/themes/montheme/myconfortplus/cookie.html?hostname=www.site.monsite.tld&origin=http://www.site.monsite.tld/_

Par contre, si j'accède directement au fichier "cookie.html" en enlevant toutes les variables, le fichier est trouvé : 
_http://www.site.monsite.tld/wp-content/themes/montheme/myconfortplus/cookie.html_

**Comment by Lausselloic** [comment]
Hello,

Désolé pour le délais, je ne suis pas expert WP. Peux-tu tester en utilisant le JS hebergé sur Github? 

<script type="text/javascript" src="https://confort-plus.orange.com/js/toolbar-min.js"></script>

**Comment by bureau2crea** [comment]
Bonjour. Je viens de tester avec votre lien en lieu et place du mien et cela fonctionne. Merci beaucoup. Puis-je l'utiliser sans risque de coupure ?

Par contre, est-il possible de remplacer le bouton par défaut "Confort+" ?

Enfin, y'a-t-il un manuel expliquant les règles à respecter pour que les fonctionnalités "Confort+" soient efficaces ?

**Comment by Lausselloic** [comment]
Oui vous pouvez utiliser ce lien sans risque de coupure, c'est celui utilisé par la page de documentation :-)

Il est possible de remplacer le bouton par un lien "custo" 
https://github.com/Orange-OpenSource/Orange-Confort-plus#deploying-orange-confort-on-your-website

`<script type="text/javascript">
accessibilitytoolbar_custom = {
// MANDATORY : ID of the target container which will include the link. If not null, activate the display in link mode. The link will be added as the last element of the target container. idLinkModeContainer : "id_target_container",

// OPTIONAL (put it as comments if useless) CSS class applied on the link to unify its appearance with the site.
cssLinkModeClassName : "linkClass",
 
// OPTIONAL (put it as comments if useless) When the service is displayed as a link in the page, a skip link is automatically added at the top of the page. If you already have a group of skip links, you can specify the target container where the skip link will be added. The link will be added as the last element of the target container. 
//idSkipLinkIdLinkMode : "", 

// OPTIONAL (put it as comments if useless) CSS class applied on the skip link
//cssSkipLinkClassName : "" 
};
</script>`

Il n'y a pas de manuel expliquant les règles à respecter :-( mais normalement en respectant le RGAA tout doit bien se passer
