### ISSUE TITLE
Orange-confort-plus intégré à mon appli VS plugin Confort + ? 

### ISSUE THREAD

**Issue by marinafernandezlyon** [Orange-OpenSource/Orange-Confort-plus#67]
Bonjour @Lausselloic , 
J'aurais deux petites questions svp : 
1- Quels sont les avantages, d'après vous, à intégrer directement Orange-Confort-Plus à un site plutôt que de faire installer à l'utilisateur le plugin Orange-Confort-Plus sur son navigateur ?
2- Est-ce que les éventuelles différences entre ces 2 solutions influencent la "note" du label accessibilité d'un site?
Merci d'avance pour vos réponses :)

**Comment by ffoodd** [comment]
Bonjour @marinafernandezlyon,

Je me permets de répondre pour Loïc :)

Le seul avantage d’installer Confort+ sur un site n’est pas pour le site lui-même mais pour Confort+ : ça fait de la publicité. Les fonctionnalités sont les mêmes, donc pour l’utilisateur aucune différence ; et pour le site, ça lui fait charger des scripts et styles supplémentaires qui seront rarement utilisés par les visiteurs. Un simple lien vers le site de Confort+ aura (a priori) le même effet que l’installation sur site, en permettant cependant aux utilisateurs de s’en servir ensuite lors de leur navigation sur d’autres sites.

Dans tous les cas, **Confort+ n’améliore pas l’accessibilité d’un site.** Aucune solution ne le permet, d’ailleurs : la seule façon d’obtenir un label avec un niveau satisfaisant est de concevoir correctement le site en prenant l’accessibilité en compte à chaque étape de sa création.

Confort+ permet aux internautes d’adapter l’affichage des sites à leurs besoins ; mais si les sites qu’ils visitent ne sont pas accessibles, Confort+ n’aura pas d’effet ou très peu.

Est-ce que ça répond à vos questions ?

**Comment by marinafernandezlyon** [comment]
Merci @ffoodd ! :)
Oui, cela répond tout à fait à mes questions !

**Comment by notabene** [comment]
> Le seul avantage d’installer Confort+ sur un site n’est pas pour le site lui-même mais pour Confort+ : ça fait de la publicité.

(Je réagis tardivement, pardon.)

Il y a quelques autres avantages à présenter la fonctionnalité directement sur un site :

* pas d'installation de plugin ni de présupposé sur la capacité de notre visiteur à l'installer (limitations techniques et/ou de compétence du visiteur)
* par voie de conséquence, la « marche à l'entrée » est plus basse
* pas de préjugé associé : la notion d'accessibilité est très subjective, un senior par exemple ne se sent pas en situation de handicap mais peut avoir besoin des adaptations proposées par un tel _widget_.

Il y a cependant une certaine complexité à l'installer sur le serveur. C'est un joli cas, je trouve, de réflexion équilibrée DX/UX (_Developer experience_ vs. _User experience_).

**Comment by marinafernandezlyon** [comment]
Merci pour ta réponse !
