### ISSUE TITLE
Activation / deactivation of the toolbar does not behave well (browser plugin)

### ISSUE THREAD

**Issue by juliemoynat** [Orange-OpenSource/Orange-Confort-plus#69]
Hi,

I'm using the Orange Confort+ toolbar as a browser plugin on some websites that can be unreadable to me. I don't use it all the time on all websites. I have several problems by using it this way.

1. When I activate the toolbar, this is activating on all websites and that's not what I expect. I don't want it to be activated on my ProtonMail browser tab or on Twitter where I have a precise custom stylesheet, etc. I would like to be able to activate it on the active tab only.
2. When I deactivate the toolbar, I often have a weird behaviour: this is deactivating for the active tab but not the others. I need to refresh the other tabs to restore the default appearance of websites. It can be really annoying if I am writing a message, for example.

Is it possible to add an option to choose if we want to activate the toolbar only on the active tab or for all tabs?
And, of course, is it possible to fix the weird behaviour on deactivating the toolbar?

**Comment by notabene** [comment]
+1 on this issue.

Team: you can find some tab-specific behaviour in [a11y.css](https://github.com/ffoodd/a11y.css) — @ffoodd has implemented it. A11y.css only applies settings to the current tab. This could be a good first step into implementing this.

**Comment by ffoodd** [comment]
Fixed with #104 (not released yet).
