### ISSUE TITLE
Two issues found with aXe DevTools

### ISSUE THREAD

**Issue by ghost** [Orange-OpenSource/Orange-Confort-plus#71]
Hi,

Two easy-to-fix issues on https://confort-plus.orange.com/index_fr (nd I guess other locales as well)

* `<meta name="viewport" content="width=device-width, initial-scale=1.0" />` needed (not provided at the moment)
* Video `iframe` has no `title` attribute.

**Comment by sdeschamps-orange** [comment]
@alexarnaud sorry for not replying sooner.

Yes, good point, too.

This project is being taken over from one team to the other at Orange and I guess all issues are going to be reviewed. Thanks for pointing it out!

**Comment by notabene** [comment]
(unassigning @denischene as this issue will most probably be taken over by the tech person who will revamp the website in the future)
