### ISSUE TITLE
Supprimer les " | " à l'enregistrement des préferences

### ISSUE THREAD

**Issue by mblanloeil** [Orange-OpenSource/Orange-Confort-plus#72]
Bonjour,

Lorsqu'on sauvegarde les préférences une requête du type <URL-SERVER>/confortplus/cookie.html?UsageConfort=1|0|user|user|0000000380350270000005000000006500000&origin=<URL-SERVER> est envoyé. 
Cette requête contient des ' | ' or ce caractère est banni si on utilise la configuration par défaut de tomcat (8.5). Cela ne respecte pas les RFC 7230 et RFC 3986. 

Est-il possible d'encoder la requête ? Ou bien changer de caractère de séparation ? 

Merci ,

**Comment by Lausselloic** [comment]
Hello, by default we don't use tomcat for confort+, but you're right it could be improve

**Comment by ffoodd** [comment]
Pour info, la nouvelle mouture en cours d’élaboration ne travaillera plus avec des _cookies_, donc ce problème sera caduque. Par ailleurs la version actuellement disponible ne subira plus de changements (sauf extrême urgence), donc je vais clore ce ticket.
