### ISSUE TITLE
Indication de disponibilité du service ConfortPlus sur un site.

### ISSUE THREAD

**Issue by Zougane** [Orange-OpenSource/Orange-Confort-plus#8]
Bonjour,
Bonne année et tous mes voeux.
Le service est super pratique mais comment l'utilisateur ayant installer son extention Chrome ou Firefox va être informé de la disponibilité du service ConfortPlus sur le site ou il se trovue ?

Pouvons-nous imaginer que l'icône du CDU affiche une notification  ou aune autre action afin d'avertir l'utilisateur ?
Zougane

**Comment by Lausselloic** [comment]
Extension mode doesn't depend on the website. If the extension is enabled, the toolbar is enabled on all visited websites
