### ISSUE TITLE
Paramètre de CDU : avoir un séparateur vertical pour identifier les autres options.

### ISSUE THREAD

**Issue by Zougane** [Orange-OpenSource/Orange-Confort-plus#9]
Bonjour,
Dans les paramètres du CDU on retrouve dans les onglets "Typography", "Layout" et "Color" plus d'une colonne de paramètre. L'espacement entre chaque colonne est trop grand. 
Le problème peut-être génant pour des personnes utilisant CDU  en complément d'une loupe d'écran; En  général cette population utilise les loupes d'écran (loupe Windows, ZoomText ou SuperNova) à un niveau de zoom très faible. Il n'en reste pas moins que l'espacement entre les 2 colonnes est plus prononcé.
L'idée pour ne pas cassé ce design serai d'ajouter des barres de séparations vertical pour les onglets "Typography" et "Layout" afin d'indiqué à l'utilisateur qu'il y a encore des trucs derrières.
Cdt, 

Zougane

**Comment by Lausselloic** [comment]
Hello,

We've updated the design of the contents, and options are now closest. Is this new design better to use for you?
